### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by ccccccourage** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#100]
导入文件时出现了这个提示，我想意思是格式不对，检查了csv文件，日期格式没有问题，测试了很多次都一样，烦请前辈帮忙看看，十分感谢！（🙇‍♀️）

（因为github不支持csv格式，原表格我用xlsx上传了，文本内容是完全一致的）
[china city gdp per capital rank fix.xlsx](https://github.com/Jannchie/Historical-ranking-data-visualization-based-on-d3.js/files/3697587/china.city.gdp.per.capital.rank.fix.xlsx)

**Comment by iplaypi** [comment]
你这个excel都打不开

**Comment by iplaypi** [comment]
检查你的csv文件表头有没有问题

**Comment by ccccccourage** [comment]
谢谢！检查表头之后发现是Date的D大写了，改成date之后问题解决
