### ISSUE TITLE
你好，我想给柱状图前的圆里面加上国旗，有什么思路吗

### ISSUE THREAD

**Issue by sunpx3** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#101]
呐，就是这里，
![image](https://user-images.githubusercontent.com/18378169/66398964-4e450300-ea11-11e9-830c-67be4fb84af0.png)
说说思路就行，我自已实现，谢谢了。

**Comment by iplaypi** [comment]
配置文件已经有了，开启即可：

  // 使用图片，会自动开启左侧圆圈显示
  use_img: true,
  // 图片路径，本地图片或者网上图片，用来设置左侧圆圈里面的logo图片，不设置就是空心圆圈
  imgs: {
    "条目": "http://i1.hdslb.com/bfs/face/983034448f81f45f05956d0455a86fe0639d6a36.jpg",
    "条目2": "d:\\1.png"
  },
