### ISSUE TITLE
如何在图像之外的水平轴上放置文本？

### ISSUE THREAD

**Issue by bj7908** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#102]
如何在图像之外的水平轴上放置文本？
가로축에 이미지말고 텍스트 어떻게 넣나요?

imgs: {
    "강남구": "img/1.jpg",         -> "강남구": "강남구",                     X

**Comment by Jannchie** [comment]
` showLabel: false, ` ->` showLabel: true;`
