### ISSUE TITLE
对于图标的一些建议

### ISSUE THREAD

**Issue by sheep-realms** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#105]
建议添加一个可以直接调用网络上的图片的功能......呃，我的描述可能不够准确，我是想说，在表中新添加一个字段，用于记录ID，然后再通过一个参数记录图片地址的基本格式，这样就可以把ID塞进去作为图片地址显示在图标上了。
例如，我想做一个记录用户数据的排行，我把每位用户的UID写在了id字段中，然后我往一个参数中写入```http://xxx.com/?size=big&uid=(一个替换占位符)```，这样的一个地址可以找到用户的头像，这样我就可以很方便地插入图标而不用一个一个写了。

**Comment by Jannchie** [comment]
这样的可定制性不够强，如果你懂程序，你可以很轻易地自己实现这一功能，但是要让不会编程的人理解什么时候id什么是占位符，不太好搞。

**Comment by sheep-realms** [comment]
@Jannchie 了解。主要是......读别人的代码是一件很头痛的事情XD
