### ISSUE TITLE
中文显示问题

### ISSUE THREAD

**Issue by cq505836696** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#108]
为什么我的网页显示的中文是乱码 ，是因为不能使用中文吗

![image](https://user-images.githubusercontent.com/42807066/70214009-9e241a00-1775-11ea-8f4b-0321e6aa5e85.png)

**Comment by generalbao** [comment]
你的编码有问题

**Comment by Jannchie** [comment]
阅读config.js第一条
