### ISSUE TITLE
Is it possible to describe another CSV format?

### ISSUE THREAD

**Issue by sxiii** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#129]
Greetings.

Rather then using CSV from Example provided, which has the form of:

```
name | type | value | date
-- | -- | -- | --
条目 | Chinese | 4E+04 | 2019-01-01
条目 | Chinese | 1E+04 | 2019-01-02
条目 | Chinese | 5E+04 | 2019-01-03
エントリ | Japanese | 1E+04 | 2019-01-03
エントリ | Japanese | 4E+04 | 2019-01-01
エントリ | Japanese | 3E+04 | 2019-01-02
Запись | Russian | 1E+04 | 2019-01-01
Запись | Russian | 2E+09 | 2019-01-02
Запись | Russian | 3E+04 | 2019-01-03
```

I would like to use the "2-dimensional" data representation model like this:
```
Country | 1/22/20 | 1/23/20 | 1/24/20 | 1/25/20
-- | -- | -- | -- | --
South Korea | 1 | 1 | 2 | 2 |  
Afghanistan | 0 | 0 | 0 | 0 |  
Albania | 0 | 0 | 0 | 0 |  
Algeria | 0 | 0 | 0 | 0 |  
```
Can you give me a hand what changes needs to be done for this to work; or it would be easier to make a shell script coverter to my format to the requested and then use it?

Thanks. D

**Comment by Jannchie** [comment]
Conversion is not supported in this project. But this requirement can be implemented using Excel's PivotTable.
