### ISSUE TITLE
BUG，柱子动画有重复

### ISSUE THREAD

**Issue by Inphon** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#130]
name | type | value | date
-- | -- | -- | --
Alienware | dell | 181 | 2019/7/2
Workstation | dell | 1648 | 2019/7/2
2-in-1 Latitude | dell | 2016 | 2019/7/2
XPS | dell | 2684 | 2019/7/2
Education | dell | 9047 | 2019/7/2
Latitude | dell | 23996 | 2019/7/2
Latitude | dell | 1 | 2019/7/3
XPS | dell | 13 | 2019/7/3
Latitude | dell | 20 | 2019/7/3
XPS | dell | 25 | 2019/7/3
Alienware | dell | 56 | 2019/7/3
Workstation | dell | 60 | 2019/7/3
XPS | dell | 70 | 2019/7/3
XPS | dell | 72 | 2019/7/3
Workstation | dell | 80 | 2019/7/3
Latitude | dell | 104 | 2019/7/3
Latitude | dell | 110 | 2019/7/3
Latitude | dell | 120 | 2019/7/3
Workstation | dell | 134 | 2019/7/3
Latitude | dell | 180 | 2019/7/3

![bg](https://user-images.githubusercontent.com/24289436/83941625-6b8bd480-a81f-11ea-9cc0-d415a117ccb0.png)

**Comment by Jannchie** [comment]
请检查数据源

**Comment by Jannchie** [comment]
当同一时间，有同样名字的数据时，就会出现这种情况。
