### ISSUE TITLE
选择example无任何反应

### ISSUE THREAD

**Issue by Gunhajing** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#131]
浏览器是谷歌。 不过example 还有data 打开都是乱码。 修改内容后仍然无反应

**Comment by Gunhajing** [comment]
jquery-3.2.1.slim.min.js:1 
Failed to load resource: net::ERR_TIMED_OUT

**Comment by Jannchie** [comment]
请检查一下是否能够连接到网络

**Comment by OnlyGarnett** [comment]
在线引用Jquery的地址失效了，把代码里https://code.jquery.com/jquery-3.2.1.slim.min.js的https的s去掉。

**Comment by OnlyGarnett** [comment]
> 浏览器是谷歌。 不过example 还有data 打开都是乱码。 修改内容后仍然无反应

乱码是因为.xls文件用的GB2312的编码方式，用.xlsx编辑然后换成.csv就可以了，csv的编码存成UTF-8。

**Comment by LeiZou** [comment]
已解决，感谢！
替换Jquery这里的到国内的CDN
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.js"></script>
