### ISSUE TITLE
为什么选择文件之后没有反应

### ISSUE THREAD

**Issue by Cat-Geek** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#132]
选择文件之后就没有反应，网速正常
![1595072393(1)](https://user-images.githubusercontent.com/57220033/87851810-c93b3280-c92e-11ea-87d2-6837a6e64b2b.png)

**Comment by OnlyGarnett** [comment]
在线引用Jquery的地址失效了，把代码里https://code.jquery.com/jquery-3.2.1.slim.min.js的https的s去掉。

**Comment by Jannchie** [comment]
你不应该选择xlsx文件，你应该导出成csv格式
