### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by jiadiantang** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#133]
报下面的这个错是什么意思？TypeError: Cannot read property 'toString' of undefined

**Comment by Jannchie** [comment]
你应该是修改了一些文件，格式出现了问题

**Comment by holly9007** [comment]
你可以先试下scr文件下的example.csv看下是没有这个问题的。我也遇到了这个提示，对比example，表头改成name | type | value | date 就好了。
