### ISSUE TITLE
[feature] 是否能按type或中文排序，或者关闭bar右边的label

### ISSUE THREAD

**Issue by ZaHChina** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#16]
目前的情况是：
bar上的文字是这样的格式  type - name 然后bar右边显示value，且按照value高到低排序

我的情况是 type是中文，希望安装type排序，例如
type1
type2
type2
type3
type3
我暂时的折中方案是把type改成对应的整型type1=3,type2=2,type3=1，然后和value列对换，这样虽然排序正确了，但bar右边显示label就变成了3，2，1，这不是我想要的，如果能关闭这个label也可以接受

**Comment by renaiss** [comment]
是先按value排序，再按type排序 还是只想按type排序？

**Comment by ZaHChina** [comment]
0基础自学了1天js，node.js，d3，webpack打包，通过修改了2处代码满足了自己的需求：
//         self.textContent = d3.format(format)(Math.round(i(t) * round) / round);
                          self.textContent = d.NewColumn;
这样就可以按value排序的同时，显示别的列的内容。。反正偶不懂编程，瞎猫撞死耗子改对了。。
