### ISSUE TITLE
GPL许可证问题

### ISSUE THREAD

**Issue by XZiar** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#17]
我看到这个项目用了GPLv3的许可证，那是不是只有同属于GPLv3的项目才能使用这个库呢（使用dist感觉也算是动态链接）？

**Comment by Jannchie** [comment]
根据我粗浅的理解，任何使用了GPL许可的项目都必须包括其源代码和 GPL 许可证副本，也就是说这是个传染协议，引入此项目的项目必须开源，当然我的理解可能也不是非常准确。
