### ISSUE TITLE
能改成后台读取数据，一打开网页就有数据可视化吗

### ISSUE THREAD

**Issue by huaji1992** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#21]
能改成后台读取数据，一打开网页就有数据可视化吗

**Comment by walterhuang23** [comment]
+1 ，我是放到了自己的文件对象储存的bucket里面了，但是网页的输入不知道怎么改成相对链接直接读取

**Comment by Jannchie** [comment]
浏览器不应该具备读取本地数据的能力，会产生跨源问题。面向一般用户的话，只能让他们自己选择文件比较方便。如果你是个业内人员，你应该能够轻而易举地自行修改读取逻辑吧。

**Comment by walterhuang23** [comment]
刚刚用python爬了数据，想在线可视化给同学看 ，可是我没有没学过js（/TДT)/

**Comment by walterhuang23** [comment]
所以问题是可以做得出来的吗? 
我问了一个做前端的，他说这个功能做不出来

**Comment by Jannchie** [comment]
你那怕是假前端。。

walterhuang23 <notifications@github.com> 于 2018年8月30日周四 18:34写道：

**Comment by titxue** [comment]
前端不知道，但后端绝对可以

Jannchie <notifications@github.com> 于2018年11月29日周四 上午3:09写道：
