### ISSUE TITLE
请问怎么修改字体

### ISSUE THREAD

**Issue by timinGo** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#25]
在stylesheet里面修改了没有反应

**Comment by tvr17** [comment]
修改stylesheet然后在根目录下运行webpack
只修改stylesheet，main没有重新生成，不会产生效果

**Comment by timinGo** [comment]
@tvr17 
WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/visual.js
Module not found: Error: Can't resolve 'd3' in '/Users/jiachen/Desktop/smart_city/Historical-ranking-data-visualization-based-on-d3.js-master/src'
 @ ./src/visual.js 8:0-25 16:19-30 108:16-25 131:17-31 133:17-28 135:17-31 137:19-31 142:18-31 149:18-29 187:16-29 238:31-37 238:61-67 238:90-96 240:30-36 245:65-78 246:65-78 268:88-101 272:32-46 276:47-56 343:28-42 347:43-52 398:80-93 454:20-34 458:35-44

ERROR in ./src/visual.js
Module not found: Error: Can't resolve 'style-loader' in '/Users/jiachen/Desktop/smart_city/Historical-ranking-data-visualization-based-on-d3.js-master'
 @ ./src/visual.js 9:0-27

**Comment by tvr17** [comment]
看着像是package.json和webpack.config.js的配置有问题吧
我不是很清楚怎么处理，我是在linux端做的，基本默认安装，几句指令就行了，windows端配置我不太清楚








------------------ 原始邮件 ------------------
发件人: "timinGo"<notifications@github.com>;
发送时间: 2018年8月30日(星期四) 下午4:51
收件人: "Jannchie/Historical-ranking-data-visualization-based-on-d3.js"<Historical-ranking-data-visualization-based-on-d3.js@noreply.github.com>;
抄送: "魏士琪"<380766574@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Jannchie/Historical-ranking-data-visualization-based-on-d3.js] 请问怎么修改字体 (#25)




@tvr17
 WARNING in configuration
 The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
 You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/
 
ERROR in ./src/visual.js
 Module not found: Error: Can't resolve 'd3' in '/Users/jiachen/Desktop/smart_city/Historical-ranking-data-visualization-based-on-d3.js-master/src'
 @ ./src/visual.js 8:0-25 16:19-30 108:16-25 131:17-31 133:17-28 135:17-31 137:19-31 142:18-31 149:18-29 187:16-29 238:31-37 238:61-67 238:90-96 240:30-36 245:65-78 246:65-78 268:88-101 272:32-46 276:47-56 343:28-42 347:43-52 398:80-93 454:20-34 458:35-44
 
ERROR in ./src/visual.js
 Module not found: Error: Can't resolve 'style-loader' in '/Users/jiachen/Desktop/smart_city/Historical-ranking-data-visualization-based-on-d3.js-master'
 @ ./src/visual.js 9:0-27

**Comment by timinGo** [comment]
@tvr17 
在mac上，报错不能读取d3跟style-loader，
