### ISSUE TITLE
调整字号

### ISSUE THREAD

**Issue by ceelzg** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#32]
在stylesheet中找到了字体，但是调整后无效。小白毫无编程经验，也根据大神的留言尝试过，很是困难，前来求助，感谢！

**Comment by Jannchie** [comment]
在stylesheet修改了字体后，需要通过webpack打包，才能生效。

**Comment by Jannchie** [comment]
现在已经不需要webpack，直接改css就行了
