### ISSUE TITLE
是否可以加入 当某个项目当前日期没有数据时保持最后一次的数据而不是消失

### ISSUE THREAD

**Issue by abc2237512422** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#33]
例如

name|type|value|date
--|--|--|--
a|a|10|2018-1-1
b|b|5|2018-1-1
a|a|20|2018-1-2
a|a|30|2018-1-3
b|b|15|2018-1-3

在```2018-1-2```时，b的数据空缺，是否可以加入一个配置项，使此时b不会消失，而是显示最后一次的数据，即 ```5```。

**Comment by MiracleXYZ** [comment]
你是说时间序列数据处理缺失值的`ffill`方法？这个可以借助数据处理工具实现。不过如果这里加入这些处理方法也是挺好的。

**Comment by Jannchie** [comment]
那么问题来了，如果b此时就是没有数据，怎么破。

**Comment by MiracleXYZ** [comment]
所以我觉得「填充缺失数据」这种事情是需要**数据处理工具**做的，而不是数据可视化工具的功能。
如果数据可视化工具擅自对原数据进行处理和改动，可能会降低工具的可信度。
