### ISSUE TITLE
how to find choose.file button

### ISSUE THREAD

**Issue by tianyifan88** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#35]
打开dist/bargraph 后没有能够在页面上找到choose.file button, 请问这个button大概在什么位置。 谢谢

**Comment by bunnyxt** [comment]
选择文件的按钮在顶部居中显示，按钮上有“浏览...”字样，你没能找到的话可能是浏览器分辨率太小导致显示不完全的问题。
