### ISSUE TITLE
在各个name前面加入logo，如何实现？

### ISSUE THREAD

**Issue by luzihang123** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#37]
尝试在数据源中，添加<img>标签，失败了。

**Comment by bunnyxt** [comment]
logo是文字还是图片呢？图片的话暂时还无法实现，文字的话直接在源文件csv中的type栏里填写就行了。

**Comment by hieulocbk** [comment]
i have already filled type. but it shows only name. Can you help?

**Comment by waitingfy** [comment]
我也需要图片的logo实现啊

**Comment by Jannchie** [comment]
已经实现了。

**Comment by waitingfy** [comment]
> 已经实现了。

谢谢

**Comment by shliang0603** [comment]
@Jannchie 楼主，请问logo加上去会在哪里显示，我简单调试了一下，更换了图片的链接也没有看到logo的显示，还请帮忙指正是什么错误（在QQ和Chrome浏览器中测试），建议楼主加入增加背景图片，就是类似更换背景颜色的效果，然后背景图片的透明度是可调节的。
