### ISSUE TITLE
能否能加类似进度条的功能

### ISSUE THREAD

**Issue by xukongop** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#4]
就是在网页端播放运行时，能随时暂停/播放、拖曳进度等

**Comment by Jannchie** [comment]
也许会加入这个功能

**Comment by xukongop** [comment]
感谢回复，在config文件中有这么一行代码
`// 每个时间节点最多显示的条目数。
    max_number : 20,`
其默认值为20，当改到50时，本以为每个柱状条的宽度会变小，但是实际未发生变化，导致相邻的柱状条发生重叠，请问在哪里修改参数会使柱状条的宽度会随max_number的值改变而改变

**Comment by Jannchie** [comment]
柱状图高度目前是写死的，修改这一部分可能需要对字体大小等等都进行调整，感觉会比较麻烦。如果你需要修改，目前只能修改源码中rect的高度再重新编译实现。你也可以通过增大图的大小来使得柱状条分散，但个人觉得条数过多显示效果不好，不建议显示那么多的条目。
