### ISSUE TITLE
调节了边距和上面文字的显示坐标后，右边的这个类别的位置调不了

### ISSUE THREAD

**Issue by Guojingxing** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#42]
![image](https://user-images.githubusercontent.com/33157458/48351130-462af900-e6c4-11e8-8fbc-6ed8c626d393.png)
职位右边的那几个字超过了这个图表的显示范围 

还有就是最下面几个进度条太长覆盖了那个日期怎么解决？

**Comment by Jannchie** [comment]
现在已经可以正常调整了
