### ISSUE TITLE
无法在柱状条显示名字了

### ISSUE THREAD

**Issue by FatinyCN** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#43]
原本在柱状条左侧（Y轴）和柱状条最右侧能显示name，更新了3天前版本（11月18日），现在显示不出来了。

**Comment by zhuyankarl** [comment]
我也遇到了这个问题

**Comment by RyanSov** [comment]
也遇到了这个问题，求解决啊

**Comment by zhuyankarl** [comment]
原来是配置的问题，我去试试

**Comment by zhuyankarl** [comment]
试了一下，确实可以，然后看配置文件里少了几个参数，计时器和计数器的开关是合并了吗？

**Comment by Jannchie** [comment]
我可能重构了代码 你最好多尝试尝试

zhuyankarl <notifications@github.com> 于 2018年11月26日周一 18:53写道：
