### ISSUE TITLE
只有一个显示标签

### ISSUE THREAD

**Issue by 4timespassedCET4** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#46]
请问图表右边有关类型的那一列无法显示该怎么解决呢，只有中间有个可以随着时间一起变得，右边魔法师那一列没有，求救

**Comment by hieulocbk** [comment]
I'am really like your project, but i have a problem.
"name" show for both y-axis and bar. "type" is not show on bar. How to solve this? Thanks!
