### ISSUE TITLE
如何把导入数据后的运行的图表保存下次可直接打开网页运行？

### ISSUE THREAD

**Issue by onewesong** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#49]

**Comment by Jannchie** [comment]
> 默认提供数据格式也可以是：[{"name": "李四","type": "战士","value": "61412","date": "01-02"},{"name": "王二麻子","type": "魔法师","value": "51243","date": "01-03"}]
> 就是变量data的值，你可以通过接口来获取数据

这是可行的，但是对不会编程的人不友好。
