### ISSUE TITLE
关于使用平台的问题

### ISSUE THREAD

**Issue by David-One** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#56]
我在win10的chrome上能使用，在win7的chrome和unbuntu18.04的chromium上不能使用，是不是这个只能在win10上使用

**Comment by Jannchie** [comment]
在win7上经过测试能够使用，Ubuntu没有测试 但是理论上也应该可以吧

**Comment by David-One** [comment]
> 在win7上经过测试能够使用，Ubuntu没有测试 但是理论上也应该可以吧

那可能是公司电脑很多更新都没有的问题吧
