### ISSUE TITLE
数据量过大时显示得会有点……不那么正常

### ISSUE THREAD

**Issue by TheBadZhang** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#6]
![](http://m.qpic.cn/psb?/V12KRNFm4IUQHS/gXYRPTgymKgH1SviWj*52wLRwlOAHtNLztaCOJGJMD8!/b/dFcAAAAAAAAA&bo=xAZDA8QGQwMCia0!&rf=viewer_4)

差不多就是这种情况了，望解决

**Comment by Jannchie** [comment]
这应该不是数据量过大出现的问题 而是你同一个日期出现了多个name相同的行
这个框架以name来区分bar，希望能够检查一下数据。

**Comment by TheBadZhang** [comment]
确实有重复的数据，感谢解答。
