### ISSUE TITLE
百分比类型无法显示，图片不知道放在哪条

### ISSUE THREAD

**Issue by solider245** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#71]
你好，见齐。刚开始使用你的软件，非常强大，不过也遇到了几个问题，希望可以帮忙解决一下：
## 1.无法支持百分比格式数据“%”

我在做英雄胜率动态条，这个游戏基本上都是百分比的数字。不知道有没有什么办法可以直接使用百分比来显示？
例如56.77%，小于1的数字无法显示，我只能将数字X100，成为56.77，曲线救国了……

## 2.图片文件不知道放在哪条

打包里只有四栏，但是我的英雄头像不知道放在哪一栏。

## 3.做好的文件不知道在哪里导出。
我以为做好了之后可以选择导出为GIF/MP4，但是找不到这个键。不知道这个是还需要自己重新去录成视频再剪辑吗？

**Comment by Jannchie** [comment]
1、config中有一个format选项，改成.2f可以支持保留两位小数。但针对百分比数据，建议乘以100，然后加一个百分号后缀。
2、图片在config文件里指定，和颜色类似。
3、导出需要自己录屏。你可以使用win10 xbox或者evcapture等工具录制。

**Comment by solider245** [comment]
收到，谢谢见齐了。

见齐 <notifications@github.com> 于2019年4月11日周四 下午1:37写道：
