### ISSUE TITLE
无法启动此程序，因为计算机中丢失USERENV.dll

### ISSUE THREAD

**Issue by lfjd05** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#73]
点击bargraph.html的时候出现此报错

**Comment by MiracleXYZ** [comment]
这个可能是启动浏览器时的报错。
请问在点击其他html文件时是否有此报错出现？
如果有，你可以尝试直接在浏览器中按`Ctrl+O`直接打开`bargraph.html`。

**Comment by lfjd05** [comment]
感谢楼上及时回复，确实如楼上所说是浏览器的问题，排除步骤：
1 查看C：\\windows\system32\USERENV.dll   是否存在，我最后发现是存在的，说明不是真的丢失了这个.dll
2 更换浏览器，我原来用的IE9，换成chrome打开一切正常
3 坑爹的IE

**Comment by MiracleXYZ** [comment]
尽量不要使用IE打开网页文件，最好使用Chrome或Firefox。
