### ISSUE TITLE
How can I "export" the video?

### ISSUE THREAD

**Issue by t2rankers** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#74]
Hello! I've finished a video by putting all the stats in it and certainly, I see a problem: is there any way to "export" the video without having to use a screen recorder? Thanks beforehand

**Comment by Envy156** [comment]
录屏软件很多的，你可以曲线救国。win10自带的也可以呀

**Comment by t2rankers** [comment]
Um, my screen recorders are pretty slow and can't record 60fps. Is there any other way?

**Comment by Envy156** [comment]
> Um, my screen recorders are pretty slow and can't record 60fps. Is there any other way?

Hello man, there are some recommended software for you, you can have a try.The first is 'bandicam' and the second is' Apowersoft '.Good luck.

**Comment by t2rankers** [comment]
> > Um, my screen recorders are pretty slow and can't record 60fps. Is there any other way?
> 
> Hello man, there are some recommended software for you, you can have a try.The first is 'bandicam' and the second is' Apowersoft '.Good luck.

I mean, I use Mac, so I don't know if I may be able to use one of them, I'll tell you later if it works. Thanks beforehand

**Comment by Envy156** [comment]
I'm sorry, man. I don't know much about macs. I'm sorry I can't help you. 
------------------
董骄      技术服务部
内蒙古赛科星精源科技有限公司    
 

联系电话：15661070762
个人邮箱：dongjiao@vip.qq.com
公司地址：内蒙古自治区呼和浩特市盛乐经济园区盛乐现代服务业集聚区金盛路与云谷大道东段交汇处



 




------------------ 原始邮件 ------------------
发件人: "t2rankers"<notifications@github.com>; 
发送时间: 2019年4月29日(星期一) 晚上8:51
收件人: "Jannchie/Historical-ranking-data-visualization-based-on-d3.js"<Historical-ranking-data-visualization-based-on-d3.js@noreply.github.com>; 
抄送: "萌新"<251345798@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Jannchie/Historical-ranking-data-visualization-based-on-d3.js]How can I "export" the video? (#74)



  
Um, my screen recorders are pretty slow and can't record 60fps. Is there any other way?
  
Hello man, there are some recommended software for you, you can have a try.The first is 'bandicam' and the second is' Apowersoft '.Good luck.
  
I mean, I use Mac, so I don't know if I may be able to use one of them, I'll tell you later if it works. Thanks beforehand
 
&mdash;

**Comment by t2rankers** [comment]
One thing, do you have any idea of why does this happen?
![wth](https://user-images.githubusercontent.com/50030729/57007835-de258c00-6beb-11e9-927c-cf5e6402faad.png)

**Comment by Envy156** [comment]
i'm so sorry,i don't konw
 
------------------
董骄      技术服务部
内蒙古赛科星精源科技有限公司    
 

联系电话：15661070762
个人邮箱：dongjiao@vip.qq.com
公司地址：内蒙古自治区呼和浩特市盛乐经济园区盛乐现代服务业集聚区金盛路与云谷大道东段交汇处



 




------------------ 原始邮件 ------------------
发件人: "t2rankers"<notifications@github.com>; 
发送时间: 2019年5月1日(星期三) 下午2:34
收件人: "Jannchie/Historical-ranking-data-visualization-based-on-d3.js"<Historical-ranking-data-visualization-based-on-d3.js@noreply.github.com>; 
抄送: "萌新"<251345798@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Jannchie/Historical-ranking-data-visualization-based-on-d3.js]How can I "export" the video? (#74)




One thing, do you have any idea of why does this happen?
 
 
&mdash;

**Comment by t2rankers** [comment]
![Captura de pantalla 2019-05-04 a la(s) 20 45 53](https://user-images.githubusercontent.com/50030729/57183467-a9e0f280-6ead-11e9-9174-fb410e1aea14.png)
And why is this milestone in the middle? Like I don't know why does this happen, but I'd like the milestones to start from the left of the graph, not the middle.

**Comment by Jannchie** [comment]
> ![Captura de pantalla 2019-05-04 a la(s) 20 45 53](https://user-images.githubusercontent.com/50030729/57183467-a9e0f280-6ead-11e9-9174-fb410e1aea14.png)
> And why is this milestone in the middle? Like I don't know why does this happen, but I'd like the milestones to start from the left of the graph, not the middle.

Modify the config.js, turn 'big_value' to false, `big_value: false,`

**Comment by Jannchie** [comment]
> Um, my screen recorders are pretty slow and can't record 60fps. Is there any other way?

If you are using Win10, you had better use the Xbox screen capture, it is able to output 60fps video.
If not, you can turn up the `interval_time` in the config.js, It will make the animation slow, then you can use PR or some other video editing software to speed up and reach 60pfs.
