### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by Jayetsu** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#75]
Hello, thanks for your code, it's awesome. I have some question about it. When I'm trying to add values over 999,999 my graph shows NaN instead of a number. Do you have any idea how to fix it? Tried to solve it by myself but I have no other ideas. Thanks!

**Comment by t2rankers** [comment]
I'd like to help you but to me, it works perfectly fine. Values over 999999 that haven't the same date as other lines will pop up as NaN, I think. I have no other ideas.

**Comment by Jayetsu** [comment]
> I'd like to help you but to me, it works perfectly fine. Values over 999999 that haven't the same date as other lines will pop up as NaN, I think. I have no other ideas.

So did you tried to use values over 999999 and it worked?

**Comment by t2rankers** [comment]
It actually did.

**Comment by Jayetsu** [comment]
Fixed by myself
