### ISSUE TITLE
Numbers are cut-off from the screen

### ISSUE THREAD

**Issue by t2rankers** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#76]
For some reason, when I watch the bar and stuff something looks weird, like the numbers if they're too high they're cut off from the screen, could you help me?
![wth](https://user-images.githubusercontent.com/50030729/56899248-49a81600-6a93-11e9-9400-c6d760b411ef.png)

**Comment by Jannchie** [comment]
In config.js, you can find `right_margin: 250,`, It is able to turn up the number to display the full number.

**Comment by t2rankers** [comment]
Thank you!
