### ISSUE TITLE
Not an issue though

### ISSUE THREAD

**Issue by t2rankers** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#79]
Hello, I'd like to know if there was any way I could like do this.
![image](https://user-images.githubusercontent.com/50030729/57318571-ed7c6c00-70fa-11e9-9384-68cec479841b.png)
I mean, putting the name on the left of the bar, because the name moving every single second looks weird and makes the name look bad in my opinion. Is there also any other way to put instead of the name inside the bar the flag?

**Comment by t2rankers** [comment]
And is there any way to remove the _type_ section?

**Comment by Jannchie** [comment]
`divide_by: "name"`
`show_bar_info: 99999`
`show_label :true`
`use_img: false`

**Comment by t2rankers** [comment]
And how do I make the bars rectangular instead of circular?

**Comment by t2rankers** [comment]
@Jannchie
