### ISSUE TITLE
How to remove names on the right

### ISSUE THREAD

**Issue by L3E7** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#81]
How do leave the names on the left and not on the right?

**Comment by t2rankers** [comment]
`divide_by: "name"
show_bar_info: 99999
show_label :true`

**Comment by L3E7** [comment]
where is show_bar?

**Comment by L3E7** [comment]
where is show_bar_info?

**Comment by L3E7** [comment]
i did all those but it still hasn’t work..

**Comment by t2rankers** [comment]
Then I don't know. That worked for me.
