### ISSUE TITLE
How to put flags

### ISSUE THREAD

**Issue by t2rankers** [Jannchie/Historical-ranking-data-visualization-based-on-d3.js#82]
I'd like to know how to put flags at the end of the bar, such as these
![image](https://user-images.githubusercontent.com/50030729/58564775-df1efd00-822d-11e9-8c43-708ef3681d5a.png)
Also is there any way to, for example, make another column that adds, for example, another number? Like, adding a column at the right of the name with the population density of a determined country.

**Comment by Jannchie** [comment]
It's not made by this project, maybe the maker of this video forked this project and enhanced it. In this project, you can add the flags in the left by edit config.js. If you are a programmer, you can do it by yourself, if not, MAYBE I will add this feature in the feature.
